# Generated by Django 5.0.2 on 2024-02-15 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_delete_test_tabl'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='test_table',
            new_name='sample',
        ),
    ]
